### ISSUE TITLE
QE 7.1 (+ Elpa?)

### ISSUE THREAD

**Issue by Chronum94** [conda-forge/qe-feedstock#28]
QE 7.1 is out for a few weeks now, but the Github mirror seems to have not been updated.

Could we have:

1. QE 7.1 from the GItlab release tar.gz?
2. Elpa support from the conda elpa package?

I've not dealt with conda feedstocks before, but I'd be willing to put work into this if I can be pointed at things that would need to be edited to do the above.

**Comment by jan-janssen** [comment]
I like the idea, do you want to start a pull request for this?

**Comment by chrisjsewell** [comment]
Heya, any update on this?
Some people require 7.1
If you point me in the right direction, I could perhaps try a PR 😄

**Comment by wolfv** [comment]
@chrisjsewell you can check & fix the open pull requests
