### ISSUE TITLE
Build for ARM architecture (linux-aarch64, mac-arm64)

### ISSUE THREAD

**Issue by chrisjsewell** [conda-forge/qe-feedstock#33]
### Comment:

Hey all,

Essentially, I would like to allow for people on Apple M chips to use QE (and @jan-janssen this extends to all of the quantum codes).

There's two ways: (1) directly via `conda install`, (2) via a docker container which has e.g. [Mambaforge-Linux-aarch64](https://github.com/conda-forge/miniforge) installed.

Is this possible?

Here's some instructions: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/, 
and also I note, you can run e.g. `CONDA_SUBDIR=linux-aarch64 conda create -n test qe`, to check if a package is available for a particular architecture.

**Comment by ltalirz** [comment]
@kjappelbaum how did you request the ARM OSX migration [here](https://github.com/conda-forge/zeopp-lsmo-feedstock/pull/4#issuecomment-1192902333) ?

**Comment by kjappelbaum** [comment]
Make a PR to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt adding the name of the package

**Comment by ltalirz** [comment]
Done https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3768

**Comment by chrisjsewell** [comment]
Thanks @ltalirz, now would just be great to work out how to also get the linux-aarch64 build 🤔

**Comment by unkcpz** [comment]
fixed by #39
